<table>
	<tr>
		<td><strong><?php echo $this->__("La misma tarjeta a&ntilde;ade m&aacute;s seguridad on-line.") ?></strong></td>
		<td>&nbsp;</td>
		<td><img src='<?php echo $this->getSkinUrl('images/paytpvcom/verifiedbyvisa.png') ?>' /></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__("Verified by Visa es un nuevo servicio que permite comprar on-line con una cofianza a&ntilde;adida.") ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__("A trav&eacute;s de un simple proceso de verificaci&oacute;n, Verified by Visa confirma su identidad cuando hace una compra en las tiendas on-line, adscritas al sistema Verified by Visa. Es pr&aacute;ctico y funciona con su propia tarjeta Visa.") ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__('Y adem&aacute;s Verified by Visa es de f&aacute;cil uso. Usted registra su tarjeta solo una vez y crea su propia contrase&ntilde;a. Cuando con dicho sistema hace una compra on-line, aparece una ventana de Verified by Visa. Simplemente introduzca su contrase&ntilde;a y haga clic. Su identidad ser&aacute; verificada y la compra asegurada.') ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__('Para activar Verified by Visa en su tarjeta Visa, o para m&aacute;s informaci&oacute;n, contacte con la entidad emisora de su tarjeta. <a href="http://www.visa.com/verified">visa.com/verified</a>.') ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3' align='center'><button class='form-button' onclick='window.close()'><?php echo $this->__('Close Window') ?></button></td>
	</tr>
</table>
